translate: Hooks inro
reactjs/nl.reactjs.org pull request #44
Opened 2019-11-30 09:59 UTC by Jacco

New PR to support suggestions

2019-12-01 12:34 UTC, degeens requested changes
Here you go... Let me know if you disagree with something. 😉

In addition to my suggestions, you should indicate that a linked article is English by using (Engels). Feel free to check the glossary & style guidelines for more info.

Thank you for your work so far! 💪

2019-12-01 12:34 UTC, degeens commented on content/docs/hooks-intro.md
> +We zullen dit verder bespreken in [De the Effect Hook](/docs/hooks-effect.html#tip-use-multiple-effects-to-separate-concerns).
```suggestion
We zullen dit verder bespreken in [De Effect Hook](/docs/hooks-effect.html#tip-use-multiple-effects-to-separate-concerns).
```

2019-12-01 12:34 UTC, degeens commented on content/docs/hooks-intro.md
> +Behalve dat het hergebruik en code organisatie moeilijke maakt, hebben we gemerkt dat classes ook een groot obstakel kunnen zijn bij het leren van React. Je moet begrijpen hoe `this` werkt in JavaScr
```suggestion
Naast dat het hergebruik en organisatie van code moeilijker maakt, hebben we gemerkt dat classes ook een groot obstakel kunnen zijn bij het leren van React. Je moet begrijpen hoe `this` werkt in JavaScript, wat heel afwijkend is van hoe dat werkt in de meeste andere talen. Je moet er aan denken om de event handlers te binden. Zonder instabiele [syntax voorstellen](https://babeljs.io/docs/en/babel-plugin-transform-class-properties/), is de code erg breedsprakig. Mensen kunnen props, state, en top-down data flow prima begrijpen maar toch worstelen met classes. Het verschil tussen functie- en class componenten in React en wanneer welke te gebruiken leidt tot onenigheid, zelfs onder ervaren React developers.
```
Small suggestions for improvement + typo.

2019-12-01 12:34 UTC, degeens commented on content/docs/hooks-intro.md
> +We begrijpen ook dat de lat voor het toevoegen van een nieuw principe aan React extreem hoog ligt. Voor nieuwsgierige lezers, hebben we een [uitgebreide RFC](https://github.com/reactjs/rfcs/pull/68)
```suggestion
We begrijpen ook dat de lat voor het toevoegen van een nieuw principe aan React extreem hoog ligt. Voor nieuwsgierige lezers hebben we een [uitgebreide RFC](https://github.com/reactjs/rfcs/pull/68) gemaakt die in meer detail duikt in de motivatie, en extra perspectief biedt op de specifieke ontwerpbeslissingen en stand van de techniek.
```

2019-12-01 15:25 UTC, Jacco commented on content/docs/hooks-intro.md
> +React biedt geen manier om herbruikbaar gedrag aan een component te "knopen" (bijvoorbeeld, om het aan een store te koppelen). Als je al een tijd met React werkt, zou je al bekend kunnen zijn met pat
Deze suggestion heeft geen wijziging.

2019-12-01 15:27 UTC, Jacco commented on content/docs/hooks-intro.md
> +Met Hooks kun je logica met state extraheren uit een component, zodat die onafhankelijk kan worden getest en hergebruikt. **Hooks laten je logica met state hergebruiken zonder aanpassingen in je comp
het slaat op "component", ik heb nagezocht dat het "de component" zou moeten zijn waarnaar je dus zou moeten verwijzen met "die". Denk ik. (Ik worstel er ook meet omdat de meeste literatuur over programmeren het steevast over "het component" heeft.

2019-12-01 15:34 UTC, Jacco commented on content/docs/hooks-intro.md
> +Om deze problemen op te lossen, **laten Hooks je meer van React's voorzieningen gebruiken zonder classes.** Conceptueel gezien zijn React componenten altijd al meer een soort functies geweest. Hooks
Het zou dan denk ik "aangeleund tegen" zijn.

2019-12-01 15:41 UTC, Jacco commented on content/docs/nav.yml
> +        title: Bouw Je Eigen Hooks
Ik ga de vertalingen verwijderen. Goed idee

2019-12-01 17:03 UTC, Jacco commented on content/docs/hooks-intro.md
> +Om deze problemen op te lossen, **laten Hooks je meer van React's voorzieningen gebruiken zonder classes.** Conceptueel gezien zijn React componenten altijd al meer een soort functies geweest. Hooks
Ik stel dit dus voor

```suggestion
Om deze problemen op te lossen, **laten Hooks je meer van React's features gebruiken zonder classes.** Conceptueel gezien hebben React componenten altijd al dichter aangeleund tegen  functies. Hooks omarmen functies, maar zonder de praktische aard van React op te offeren. Hooks bieden toegang tot imperatieve ontsnappingsluiken en vereisen niet dat je complexe functional of reactive programmeertechnieken leert.
```

2019-12-01 20:04 UTC, degeens commented on content/docs/hooks-intro.md
> +Om deze problemen op te lossen, **laten Hooks je meer van React's voorzieningen gebruiken zonder classes.** Conceptueel gezien zijn React componenten altijd al meer een soort functies geweest. Hooks
Good point. I agree with your suggestion above.

2019-12-02 17:04 UTC, degeens commented on content/docs/hooks-intro.md
> +Met Hooks kun je logica met state extraheren uit een component, zodat die onafhankelijk kan worden getest en hergebruikt. **Hooks laten je logica met state hergebruiken zonder aanpassingen in je comp
If I'm not mistaken, it refers to 'logica met state' and not 'component'. I personally think it feels more natural, but I may be wrong. Maybe we need a third opinion?

2019-12-03 12:39 UTC, degeens commented on content/docs/nav.yml
> +        title: Introducie tot Hooks
```suggestion
        title: Introductie tot Hooks
```
Typo

2019-12-03 18:18 UTC, Jacco commented on content/docs/hooks-intro.md
> +Met Hooks kun je logica met state extraheren uit een component, zodat die onafhankelijk kan worden getest en hergebruikt. **Hooks laten je logica met state hergebruiken zonder aanpassingen in je comp
You are right about it refering to 'logica met state'.

Discussed this one with my wife, she says we are both wrong...

She says it should be "hij" or "deze".

I like "deze" best:
```suggestion
Met Hooks kun je logica met state extraheren uit een component, zodat deze onafhankelijk kan worden getest en hergebruikt. **Hooks laten je logica met state hergebruiken zonder aanpassingen in je componenten hiërarchie.** Dit maakt het eenvoudig om Hooks te delen met componenten of met de community.
```

2019-12-03 18:51 UTC, degeens commented on content/docs/hooks-intro.md
> +Met Hooks kun je logica met state extraheren uit een component, zodat die onafhankelijk kan worden getest en hergebruikt. **Hooks laten je logica met state hergebruiken zonder aanpassingen in je comp
I agree with your wife, 'deze' is better indeed. 😁

2019-12-04 12:30 UTC, degeens commented on content/docs/hooks-intro.md
> +In veel gevallen is het niet mogelijk om deze componenten op te splitsen in kleinere componenten omdat de logica met state overal verspreid is. Het is ook moeilijk om ze te testen. Dit is één van de
```suggestion
In veel gevallen is het niet mogelijk om deze componenten op te splitsen in kleinere componenten omdat de logica met state overal verspreid is. Het is ook moeilijk om ze te testen. Dit is één van de redenen waarom veel mensen verkiezen om React te combineren met een aparte state management library. Maar dat introduceert vaak te veel abstractie, je moet steeds tussen verschillende bestanden heen en weer springen, en het maakt hergebruik van componenten moeilijker.
```

2019-12-04 12:35 UTC, degeens commented on content/docs/hooks-intro.md
> +Naast het moeilijker maken van hergebruik en organisatie van code, hebben we gemerkt dat classes ook een groot obstakel kunnen zijn bij het leren van React. Je moet begrijpen hoe `this` werkt in Java
```suggestion
Naast het moeilijker maken van hergebruik en organisatie van code, hebben we gemerkt dat classes ook een groot obstakel kunnen zijn bij het leren van React. Je moet begrijpen hoe `this` werkt in JavaScript, wat heel afwijkend is van hoe dat werkt in de meeste andere talen. Je moet er aan denken om de event handlers te binden. Zonder instabiele [syntax voorstellen (Engels)](https://babeljs.io/docs/en/babel-plugin-transform-class-properties/), is de code erg breedsprakig. Mensen kunnen props, state en top-down data flow prima begrijpen maar toch worstelen met classes. Het verschil tussen functie- en class componenten in React en wanneer welke te gebruiken leidt tot onenigheid, zelfs onder ervaren React developers.
```
Unnecessary comma.

2019-12-04 16:29 UTC, degeens approved these changes

2019-12-04 16:36 UTC, Jacco commented
@Keraito can you also review?

2019-12-10 09:59 UTC, Keraito approved these changes
Looks good in general, awesome work! I've got a few comments and also suggestions, so please look into those!

2019-12-10 09:59 UTC, Keraito commented on content/docs/hooks-intro.md
> +In veel gevallen is het niet mogelijk om deze componenten op te splitsen in kleinere componenten omdat de logica met state overal verspreid is. Het is ook moeilijk om ze te testen. Dit is één van de
```suggestion
In veel gevallen is het niet mogelijk om deze componenten op te splitsen in kleinere componenten omdat de logica met state overal verspreid is. Het is ook moeilijk om ze te testen. Dit is één van de redenen waarom veel mensen ervoor kiezen om React te combineren met een aparte state management library, maar dat introduceert vaak te veel abstractie. Je moet constant tussen verschillende bestanden heen en weer springen en het maakt hergebruik van componenten moeilijker.
```

2019-12-10 09:59 UTC, Keraito commented on content/docs/hooks-intro.md
> +Om dit op te lossen **laten Hooks je een component opsplitsen in kleinere functies gebaseerd op welke onderdelen gerelateerd zijn (zoals het opzetten van een subscription of het ophalen van data)**,
```suggestion
Om dit op te lossen **laten Hooks je een component opsplitsen in kleinere functies gebaseerd op welke onderdelen gerelateerd zijn (zoals het opzetten van een subscription of het ophalen van data)**, in plaats van splitsingen te forceren op basis van lifecycle methoden. Je kunt ook ervoor kiezen om de lokale state van een component te managen met een reducer om hem voorspelbaarder te maken.
```

2019-12-10 09:59 UTC, Keraito commented on content/docs/hooks-intro.md
> +Naast het moeilijker maken van hergebruik en organisatie van code, hebben we gemerkt dat classes ook een groot obstakel kunnen zijn bij het leren van React. Je moet begrijpen hoe `this` werkt in Java
```suggestion
Naast het moeilijker maken van hergebruik en organisatie van code hebben we gemerkt dat classes ook een groot obstakel kunnen zijn bij het leren van React. Je moet begrijpen hoe `this` werkt in JavaScript, wat heel afwijkend is van hoe dat werkt in de meeste andere talen. Je moet er aan denken om de event handlers te binden. Zonder instabiele [syntax voorstellen (Engels)](https://babeljs.io/docs/en/babel-plugin-transform-class-properties/) is de code erg breedsprakig. Mensen kunnen props, state en top-down data flow prima begrijpen maar toch worstelen met classes. Het verschil tussen functie- en class componenten in React en wanneer je welke moet gebruiken leidt tot onenigheid, zelfs onder ervaren React developers.
```

2019-12-10 21:21 UTC, Jacco commented on content/docs/hooks-intro.md
> +Om dit op te lossen **laten Hooks je een component opsplitsen in kleinere functies gebaseerd op welke onderdelen gerelateerd zijn (zoals het opzetten van een subscription of het ophalen van data)**,
```suggestion
Om dit op te lossen **laten Hooks je een component opsplitsen in kleinere functies gebaseerd op welke onderdelen gerelateerd zijn (zoals het opzetten van een subscription of het ophalen van data)**, in plaats van splitsingen te forceren op basis van lifecycle methoden. Je kunt er ook voor kiezen om de lokale state van een component te managen met een reducer, om hem voorspelbaarder te maken.
```

2019-12-10 21:34 UTC, Jacco commented on content/docs/hooks-intro.md
> +Voor we verder gaan, Hooks zijn:
```suggestion
Merk voordat we verder gaan op: Hooks zijn:
```

2019-12-10 21:40 UTC, Jacco commented on content/docs/hooks-intro.md
> +## Introductievideo {#video-introduction}
I think so.

https://www.linguee.nl/engels-nederlands/vertaling/introductory+video.html

2019-12-10 21:46 UTC, Jacco commented on content/docs/hooks-intro.md
> +        Klik op me
Van het spaans:
https://es.reactjs.org/docs/hooks-intro.html

En onze oosterburen:
https://de.reactjs.org/docs/hooks-intro.html

Spaans dus wel comments niet display waarden.
Duits wel beide vertaald.

Ik vind vertalen beter, tenzij haar het voorbeeld wordt verwezen in een "Pen"

2019-12-10 21:51 UTC, Jacco commented on content/docs/hooks-intro.md
> +### Het is moeilijk om logica met state te hergebruiken in componenten {#its-hard-to-reuse-stateful-logic-between-components}
https://github.com/reactjs/nl.reactjs.org/issues/5

But this heading didn't have capitals

2019-12-10 21:55 UTC, Jacco commented
@Keraito thx for the review

Changed a few of the suggestions slightly.

Only three thing left to discuss:
[https://github.com/reactjs/nl.reactjs.org/pull/44/files](https://github.com/reactjs/nl.reactjs.org/pull/44/files)

2019-12-30 08:27 UTC, Keraito commented
Looks good, need to trigger a rebuild of some kind and then merge

2020-01-06 18:38 UTC, Jacco commented
> Looks good, need to trigger a rebuild of some kind and then merge

You mean the ci/circle build?

2020-01-06 18:55 UTC, Keraito commented
Yes

2020-01-06 21:30 UTC, Jacco commented
For the sync PRs it runs automayically...

2020-05-23 06:21 UTC, merged